export const SRC: Record<string, string> = {
 "f0": "flowchart TB\nsubgraph R1[\"Stages 01–03\"]\ndirection LR\nA(\"<span class='n'>[01]</span><b>Candidate profile</b><br/><span class='s'>resume-derived context</span>\") --> B(\"<span class='n'>[02]</span><b>Matched roles</b><br/><span class='s'>automatic surfacing</span>\") --> C(\"<span class='n'>[03]</span><b>Direct application</b><br/><span class='s'>same workflow</span>\")\nend\nsubgraph R2[\"Stages 04–05\"]\ndirection LR\nD(\"<span class='n'>[04]</span><b>AI interview</b><br/><span class='s'>multi-stage agents</span>\") --> E(\"<span class='n'>[05]</span><b>Evaluation / ranking</b><br/><span class='s'>structured signals</span>\")\nend\nR1 --> R2\nclassDef key stroke-width:1px",
 "f1": "flowchart TB\nsubgraph EMP[\"Employer journey\"]\nE1(\"<span class='n'>[01]</span><b>Role brief</b>\") --> E2(\"<span class='n'>[02]</span><b>Structured role</b>\") --> E3(\"<span class='n'>[03]</span><b>Distribution</b>\") --> E4(\"<span class='n'>[04]</span><b>Interview template</b>\")\nend\nsubgraph CAN[\"Candidate journey\"]\nC1(\"<span class='n'>[01]</span><b>Resume</b>\") --> C2(\"<span class='n'>[02]</span><b>Candidate profile</b>\") --> C3(\"<span class='n'>[03]</span><b>Matched roles</b>\") --> C4(\"<span class='n'>[04]</span><b>Application</b>\") --> C5(\"<span class='n'>[05]</span><b>AI interview</b>\")\nend\nE4 --> EV(\"<span class='n'>[05]</span><b>Evaluation</b>\")\nC5 --> EV\nclassDef key stroke-width:1px",
 "f2": "flowchart TB\nsubgraph R1[\"Stages 01–03\"]\ndirection LR\nA(\"<span class='n'>[01]</span><b>Resume</b><br/><span class='s'>input</span>\") --> B(\"<span class='n'>[02]</span><b>Parse + extract</b><br/><span class='s'>structured information</span>\") --> C(\"<span class='n'>[03]</span><b>Normalize skills</b><br/><span class='s'>normalized skills</span>\")\nend\nsubgraph R2[\"Stages 04–06\"]\ndirection LR\nD(\"<span class='n'>[04]</span><b>Summary + context</b><br/><span class='s'>professional + experience</span>\") --> E(\"<span class='n'>[05]</span><b>Skill embeddings</b><br/><span class='s'>vector signal</span>\") --> F(\"<span class='n'>[06]</span><b>Signals + score</b><br/><span class='s'>matching + composite</span>\")\nend\nR1 --> R2\nclassDef key stroke-width:1px",
 "f3": "flowchart LR\nA(\"<span class='n'>[01]</span><b>Candidate profile</b><br/><span class='s'>reused context</span>\") --> B(\"<span class='n'>[02]</span><b>Matched roles</b><br/><span class='s'>automatically surfaced</span>\") --> C(\"<span class='n'>[03]</span><b>Direct application</b><br/><span class='s'>same workflow</span>\") --> D(\"<span class='n'>[04]</span><b>AI interview</b><br/><span class='s'>structured multi-stage</span>\")\nclassDef key stroke-width:1px",
 "f4": "flowchart TB\nsubgraph R1[\"Stages 01–03\"]\ndirection LR\nA(\"<span class='n'>[01]</span><b>Role brief</b><br/><span class='s'>employer input</span>\") --> B(\"<span class='n'>[02]</span><b>Celery</b><br/><span class='s'>async processing</span>\") --> C(\"<span class='n'>[03]</span><b>Structured-output LLM</b><br/><span class='s'>JD generation</span>\")\nend\nsubgraph R2[\"Stages 04–05\"]\ndirection LR\nD(\"<span class='n'>[04]</span><b>Pydantic</b><br/><span class='s'>structured validation</span>\") --> E(\"<span class='n'>[05]</span><b>Interview-ready role</b><br/><span class='s'>JD + screening + requirements</span>\")\nend\nR1 --> R2\nclassDef key stroke-width:1px",
 "f5": "flowchart LR\nA(\"<span class='n'>[01]</span><b>Technical</b>\") --> B(\"<span class='n'>[02]</span><b>Experience</b>\") --> C(\"<span class='n'>[03]</span><b>Coding</b>\") --> D(\"<span class='n'>[04]</span><b>Q&amp;A</b>\")\nclassDef key stroke-width:1px",
 "f6": "flowchart LR\nL1(\"<span class='n'>[01]</span><b>Data Intelligence</b><br/><span class='s'>Candidate profiles<br/>Job data<br/>Embeddings<br/>Matching signals</span>\") --> L2(\"<span class='n'>[02]</span><b>AI Engine</b><br/><span class='s'>Resume parsing<br/>JD generation<br/>Interviews<br/>Evaluation</span>\") --> L3(\"<span class='n'>[03]</span><b>Workflow Layer</b><br/><span class='s'>Job creation<br/>Pipeline<br/>Scheduling<br/>Communications</span>\") --> L4(\"<span class='n'>[04]</span><b>Decision Layer</b><br/><span class='s'>Ranking<br/>Analytics<br/>Conversion<br/>Role insights</span>\")\nclassDef key stroke-width:1px",
 "f7": "flowchart TB\nD(\"<b>Distribution</b>\") --> A(\"<span class='n'>[01]</span><b>Career pages</b>\")\nD --> B(\"<span class='n'>[02]</span><b>Google Jobs</b>\")\nD --> C(\"<span class='n'>[03]</span><b>LinkedIn</b>\")\nD --> E(\"<span class='n'>[04]</span><b>Greenhouse</b>\")\nD --> F(\"<span class='n'>[05]</span><b>Calendars</b>\")\nclassDef key stroke-width:1px"
};
export const THEME_CSS = ".node rect,.node polygon{fill:color-mix(in srgb,var(--foreground) 9%,var(--card))!important;stroke:color-mix(in srgb,var(--foreground) 14%,var(--card))!important;stroke-width:1px!important;rx:0;ry:0}\n.node.key rect{fill:color-mix(in srgb,var(--foreground) 18%,var(--card))!important;stroke:var(--foreground)!important}\n.nodeLabel,.label,.label div,.label span{color:var(--foreground)!important;font-family:var(--font-sans)!important;font-size:13px;line-height:1.45;text-align:left!important;white-space:nowrap!important}\n.label .n,.nodeLabel .n{color:color-mix(in srgb,var(--foreground) 60%,transparent)!important;font-size:11px!important;font-weight:400!important;margin-right:8px}\nb{font-weight:500;letter-spacing:-.011em}\n.label .s,.nodeLabel .s{display:inline-block;color:color-mix(in srgb,var(--foreground) 68%,transparent)!important;font-weight:400!important;font-size:11px!important;line-height:1.4}\n.cluster rect{fill:transparent!important;stroke:var(--border)!important;stroke-dasharray:3 3;rx:6;ry:6}\n.cluster-label .nodeLabel,.cluster-label span{font-size:11px!important;font-weight:600!important;letter-spacing:.06em;text-transform:uppercase;color:var(--muted-foreground)!important}\n.flowchart-link{stroke:var(--muted-foreground)!important;stroke-width:1px!important;fill:none}\n.edgeLabel{background:var(--card)}";
export const IDS: string[] = ["s1","s2","s3","s4","s5"];
export const TOC: string[][] = [["1","Product flow","s1"],["2","Candidates","s2"],["3","Roles & interviews","s3"],["4","Architecture","s4"],["5","Results","s5"]];
