export const SRC: Record<string, string> = {
 "f0": "flowchart TB\nA(\"<span class='n'>[01]</span><b>Creator dashboard</b><br/><span class='s'>profile · themes · tools</span>\") --> B(\"<span class='n'>[02]</span><b>Bento editor</b>\")\nA --> C(\"<span class='n'>[03]</span><b>Commerce</b>\")\nA --> D(\"<span class='n'>[04]</span><b>Analytics</b>\")\nA --> E(\"<span class='n'>[05]</span><b>AI / Manager</b>\")\nB --> F(\"<span class='n'>[06]</span><b>Public creator page</b><br/><span class='s'>tenant-resolved experience</span>\")\nC --> F\nD --> F\nE --> F\nclassDef key stroke-width:1px",
 "f1": "flowchart TB\nA(\"<span class='n'>[01]</span><b>Creator edit</b><br/><span class='s'>drag · resize · content</span>\") --> B(\"<span class='n'>[02]</span><b>React Grid Layout</b><br/><span class='s'>bento composition</span>\")\nB --> C(\"<span class='n'>[03]</span><b>React Context</b><br/><span class='s'>shared editor state</span>\")\nC --> D1(\"<span class='n'>[04A]</span><b>Desktop items</b><br/><span class='s'>12-column layout</span>\")\nC --> D2(\"<span class='n'>[04B]</span><b>Mobile items</b><br/><span class='s'>2-column layout</span>\")\nD1 --> E(\"<span class='n'>[05]</span><b>Synchronized layout mapping</b>\")\nD2 --> E\nE --> F(\"<b>items_data</b><br/><span class='s'>profile · items · theme</span>\")\nF --> G(\"<span class='n'>[06]</span><b>Supabase</b><br/><span class='s'>persisted page config</span>\")\nclassDef key stroke-width:1px",
 "f2": "flowchart TB\nsubgraph R1[\"Part 1\"]\ndirection LR\nA(\"<b>Creator action</b>\") --> B(\"<b>React state</b>\") --> C(\"<b>Unsaved</b>\")\nend\nsubgraph R2[\"Part 2\"]\ndirection LR\nD(\"<b>2.5-second save window</b>\") --> E(\"<b>Supabase update</b>\") --> F(\"<b>Saved state</b>\")\nend\nR1 --> R2\nclassDef key stroke-width:1px",
 "f3": "flowchart TB\nA(\"<b>Cloudflare custom hostname</b>\") --> B(\"<b>Validate hostname</b><br/><span class='s'>custom hostname state checks</span>\")\nB --> C(\"<b>DNS config</b><br/><span class='s'>required records</span>\")\nC --> D(\"<b>Status + SSL polling</b><br/><span class='s'>every 15 s · TLS 1.2+</span>\")\nD --> E(\"<b>Active custom domain</b><br/><span class='s'>verified creator hostname</span>\")\nE --> G(\"<b>Tenant / hostname resolver</b><br/><span class='s'>middleware rewrite</span>\")\nS(\"<b>username.pocketlink.co</b><br/><span class='s'>Pocketlink subdomain</span>\") --> G\nG --> H(\"<b>Public creator page</b><br/><span class='s'>server tenant + client grid</span>\")\nclassDef key stroke-width:1px",
 "f4": "flowchart TB\nA(\"<span class='n'>[01]</span><b>Product block</b><br/><span class='s'>creator page commerce</span>\") --> B(\"<span class='n'>[02]</span><b>Cart</b><br/><span class='s'>inventory + discount</span>\")\nB --> C(\"<span class='n'>[03]</span><b>Three-click checkout</b><br/><span class='s'>address · shipping · payment</span>\")\nC --> D(\"<span class='n'>[04]</span><b>Order state</b><br/><span class='s'>payment + webhook</span>\")\nD --> E1(\"<span class='n'>[05A]</span><b>Shipping</b><br/><span class='s'>physical fulfilment</span>\")\nD --> E2(\"<span class='n'>[05B]</span><b>Digital access</b><br/><span class='s'>ownership-gated</span>\")\nclassDef key stroke-width:1px",
 "f5": "flowchart TB\nA(\"<span class='n'>[01]</span><b>Public browser</b><br/><span class='s'>creator page visitor</span>\") --> B(\"<span class='n'>[02]</span><b>Visitor / session</b><br/><span class='s'>identity + session state</span>\")\nB --> C(\"<span class='n'>[03]</span><b>Event capture</b><br/><span class='s'>sessions + interactions</span>\")\nC --> D1(\"<span class='n'>[04A]</span><b>30+ signals</b><br/><span class='s'>clicks · attention · scroll</span>\")\nC --> D2(\"<span class='n'>[04B]</span><b>Heatmap buffer</b><br/><span class='s'>local batch flush</span>\")\nD1 --> E(\"<span class='n'>[05]</span><b>PostHog + Supabase</b><br/><span class='s'>analytics data model</span>\")\nD2 --> E\nE --> F(\"<span class='n'>[06]</span><b>Creator view</b><br/><span class='s'>business context</span>\")\nclassDef key stroke-width:1px",
 "f6": "flowchart TB\nsubgraph R1[\"Stages 01–04\"]\ndirection LR\nA(\"<span class='n'>[01]</span><b>GitHub push</b>\") --> B(\"<span class='n'>[02]</span><b>Actions CI</b>\") --> C(\"<span class='n'>[03]</span><b>Buildx</b>\") --> D(\"<span class='n'>[04]</span><b>Docker image</b>\")\nend\nsubgraph R2[\"Stages 05–07\"]\ndirection LR\nE(\"<span class='n'>[05]</span><b>Docker Hub</b>\") --> F(\"<span class='n'>[06]</span><b>Actions CD</b>\") --> G(\"<span class='n'>[07]</span><b>AWS EKS</b>\")\nend\nR1 --> R2\nclassDef key stroke-width:1px"
};
export const THEME_CSS = ".node rect,.node polygon{fill:color-mix(in srgb,var(--foreground) 9%,var(--card))!important;stroke:color-mix(in srgb,var(--foreground) 14%,var(--card))!important;stroke-width:1px!important;rx:0;ry:0}\n.node.key rect{fill:color-mix(in srgb,var(--foreground) 18%,var(--card))!important;stroke:var(--foreground)!important}\n.nodeLabel,.label,.label div,.label span{color:var(--foreground)!important;font-family:var(--font-sans)!important;font-size:13px;line-height:1.45;text-align:left!important;white-space:nowrap!important}\n.label .n,.nodeLabel .n{color:color-mix(in srgb,var(--foreground) 60%,transparent)!important;font-size:11px!important;font-weight:400!important;margin-right:8px}\nb{font-weight:500;letter-spacing:-.011em}\n.label .s,.nodeLabel .s{display:inline-block;color:color-mix(in srgb,var(--foreground) 68%,transparent)!important;font-weight:400!important;font-size:11px!important;line-height:1.4}\n.cluster rect{fill:transparent!important;stroke:var(--border)!important;stroke-dasharray:3 3;rx:6;ry:6}\n.cluster-label .nodeLabel,.cluster-label span{font-size:11px!important;font-weight:600!important;letter-spacing:.06em;text-transform:uppercase;color:var(--muted-foreground)!important}\n.flowchart-link{stroke:var(--muted-foreground)!important;stroke-width:1px!important;fill:none}\n.edgeLabel{background:var(--card)}";
export const IDS: string[] = ["s1","s2","s3","s4","s5"];
export const TOC: string[][] = [["1","Product","s1"],["2","Editor","s2"],["3","Domains & commerce","s3"],["4","Analytics & AI","s4"],["5","Delivery","s5"]];
