export const SRC: Record<string, string> = {
 "f0": "flowchart TB\nsubgraph R1[\"Stages 01–03\"]\ndirection LR\nA(\"<span class='n'>[01]</span><b>Upload material</b>\") --> B(\"<span class='n'>[02]</span><b>Course evidence</b>\") --> C(\"<span class='n'>[03]</span><b>Agentic RAG</b>\")\nend\nsubgraph R2[\"Stages 04–05\"]\ndirection LR\nD(\"<span class='n'>[04]</span><b>Grounding gate</b>\") --> E(\"<span class='n'>[05]</span><b>Cite or review</b>\")\nend\nR1 --> R2\nclassDef key stroke-width:1px",
 "f1": "flowchart TB\nA(\"<span class='n'>[01]</span><b>Student</b><br/><span class='s'>course workspace</span>\") --> B(\"<span class='n'>[02]</span><b>Frontend</b><br/><span class='s'>Next.js / React</span>\")\nB --> C(\"<span class='n'>[03]</span><b>Supabase Auth</b><br/><span class='s'>session + bearer</span>\")\nC --> D(\"<span class='n'>[04]</span><b>Server / API Gateway</b><br/><span class='s'>user validation, FastAPI gateway</span>\")\nD --> E(\"<span class='n'>[05]</span><b>Doc Processing</b><br/><span class='s'>Storage · OCR · pgvector</span>\")\nD --> F(\"<span class='n'>[06]</span><b>RAG Chat</b><br/><span class='s'>pgvector · memory · Gemini</span>\")\nD --> G(\"<span class='n'>[07]</span><b>Practice</b><br/><span class='s'>pgvector · Gemini</span>\")\nclassDef key stroke-width:1px",
 "f2": "flowchart TB\nP(\"<span class='n'>[01]</span><b>Preferences</b><br/><span class='s'>stored student context</span>\") --> C(\"<span class='n'>[03]</span><b>Context</b><br/><span class='s'>evidence + history</span>\")\nE(\"<span class='n'>[02]</span><b>Course evidence</b><br/><span class='s'>scoped vector search</span>\") --> C\nC --> G(\"<span class='n'>[04]</span><b>Gemini</b><br/><span class='s'>answer generation</span>\")\nG --> GR{\"<span class='n'>[05]</span><b>Grounding</b><br/><span class='s'>evidence check</span>\"}\nGR -->|\"PASS\"| CI(\"<b>Citations</b><br/><span class='s'>map to sources</span>\")\nGR -->|\"LOW\"| HR(\"<b>Human review</b><br/><span class='s'>review / revise</span>\")\nCI --> S(\"<span class='n'>[06]</span><b>Stream</b>\")\nHR --> S\nS --> PE(\"<span class='n'>[07]</span><b>Persist</b>\")\nclassDef key stroke-width:1px",
 "f3": "flowchart TB\nA(\"<span class='n'>[01]</span><b>Knowledge</b><br/><span class='s'>pgvector</span>\")\nB(\"<span class='n'>[02]</span><b>Session</b><br/><span class='s'>semantic recall</span>\")\nC(\"<span class='n'>[03]</span><b>Preferences</b><br/><span class='s'>Mem0</span>\")\nD(\"<span class='n'>[04]</span><b>Agent state</b><br/><span class='s'>LangGraph checkpoints</span>\")\nclassDef key stroke-width:1px",
 "f4": "flowchart TB\nA(\"<span class='n'>[01]</span><b>Change</b><br/><span class='s'>prompt / retrieval</span>\") --> B(\"<span class='n'>[02]</span><b>500+ suite</b><br/><span class='s'>8 domains</span>\")\nB --> C(\"<span class='n'>[03]</span><b>Evaluators</b><br/><span class='s'>RAGAS · DeepEval · LLM-as-judge</span>\")\nC --> D(\"<span class='n'>[04]</span><b>Quality report</b><br/><span class='s'>faithfulness + relevance</span>\")\nD --> E{\"<span class='n'>[05]</span><b>Quality gate</b><br/><span class='s'>release decision</span>\"}\nE -->|\"PASS\"| F(\"<b>Release</b><br/><span class='s'>ship change</span>\")\nE -->|\"FAIL\"| G(\"<b>Revise</b><br/><span class='s'>prompt / retrieval</span>\")\nG --> A\nclassDef key stroke-width:1px",
 "f5": "flowchart TB\nsubgraph R1[\"Stages 01–03\"]\ndirection LR\nA(\"<span class='n'>[01]</span><b>Upload</b>\") --> B(\"<span class='n'>[02]</span><b>Extract</b>\") --> C(\"<span class='n'>[03]</span><b>Normalize</b>\")\nend\nsubgraph R2[\"Stages 04–06\"]\ndirection LR\nD(\"<span class='n'>[04]</span><b>Chunk</b>\") --> E(\"<span class='n'>[05]</span><b>Embed</b>\") --> F(\"<span class='n'>[06]</span><b>pgvector</b>\")\nend\nR1 --> R2\nclassDef key stroke-width:1px",
 "f6": "flowchart TB\nsubgraph R1[\"Stages 01–03\"]\ndirection LR\nA(\"<span class='n'>[01]</span><b>Browser</b>\") --> B(\"<span class='n'>[02]</span><b>Supabase Auth</b>\") --> C(\"<span class='n'>[03]</span><b>Next.js API</b>\")\nend\nsubgraph R2[\"Stages 04–05\"]\ndirection LR\nD(\"<span class='n'>[04]</span><b>FastAPI gateway</b>\") --> E(\"<span class='n'>[05]</span><b>User scope</b><br/><span class='s'>user / course / material</span>\")\nend\nR1 --> R2\nclassDef key stroke-width:1px",
 "f7": "flowchart TB\nsubgraph R1[\"Stages 01–04\"]\ndirection LR\nA(\"<span class='n'>[01]</span><b>GitHub Actions</b>\") --> B(\"<span class='n'>[02]</span><b>Test / Build</b>\") --> C(\"<span class='n'>[03]</span><b>Docker image</b>\") --> D(\"<span class='n'>[04]</span><b>Push image</b>\")\nend\nsubgraph R2[\"Stages 05–07\"]\ndirection LR\nE(\"<span class='n'>[05]</span><b>K8s deploy</b>\") --> F(\"<span class='n'>[06]</span><b>AWS EKS</b>\") --> G(\"<span class='n'>[07]</span><b>Health</b>\")\nend\nR1 --> R2\nclassDef key stroke-width:1px"
};
export const THEME_CSS = ".node rect,.node polygon{fill:color-mix(in srgb,var(--foreground) 9%,var(--card))!important;stroke:color-mix(in srgb,var(--foreground) 14%,var(--card))!important;stroke-width:1px!important;rx:0;ry:0}\n.node.key rect{fill:color-mix(in srgb,var(--foreground) 18%,var(--card))!important;stroke:var(--foreground)!important}\n.nodeLabel,.label,.label div,.label span{color:var(--foreground)!important;font-family:Inter,system-ui,sans-serif!important;font-size:13px;line-height:1.45;text-align:left!important;white-space:nowrap!important}\n.label .n,.nodeLabel .n{color:color-mix(in srgb,var(--foreground) 60%,transparent)!important;font-size:11px!important;font-weight:400!important;margin-right:8px}\nb{font-weight:500;letter-spacing:-.011em}\n.label .s,.nodeLabel .s{display:inline-block;color:color-mix(in srgb,var(--foreground) 68%,transparent)!important;font-weight:300!important;font-size:11px!important;line-height:1.4}\n.cluster rect{fill:transparent!important;stroke:var(--border)!important;stroke-dasharray:3 3;rx:6;ry:6}\n.cluster-label .nodeLabel,.cluster-label span{font-size:11px!important;font-weight:600!important;letter-spacing:.06em;text-transform:uppercase;color:var(--muted-foreground)!important}\n.flowchart-link{stroke:var(--muted-foreground)!important;stroke-width:1px!important;fill:none}\n.edgeLabel{background:var(--card)}";
export const IDS: string[] = ["s1","s2","s3","s4","s5"];
export const TOC: string[][] = [["1","System","s1"],["2","Agentic RAG","s2"],["3","Evaluation","s3"],["4","Deployment","s4"],["5","Results","s5"]];
